"""empty message

Revision ID: df02d8b86f71
Revises: 22f2b1173a0b
Create Date: 2025-10-07 06:49:32.706358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df02d8b86f71'
down_revision = '22f2b1173a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_pokeballs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokeball_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokeball_id'], ['pokeballs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pokeball_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pokeball_id'], ['pokeballs.id'], name='media_pokeball_id_fkey'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], name='media_pokemon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='media_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='media_pkey')
    )
    op.drop_table('favorite_pokeballs')
    # ### end Alembic commands ###
